version: "3"
services:

  # 定义一个名为 tsai-monitor 的服务
  tsai-monitor:
    # 指定容器所使用的镜像名称为 tsai-monitor
    image: tsai-monitor:latest
    # 指定容器的名称为 tsai-monitor
    container_name: tsai-monitor
    privileged: false
    # 设置容器的自动重启策略为 always，即容器总是重新启动
    restart: always
    build:
      # 指定构建该服务的上下文路径，即 Dockerfile 所在的目录
      context: .
      # 指定 Dockerfile 文件路径
      dockerfile: ./Dockerfile
    # 暴露容器的端口映射，将容器的端口映射到主机端口
    ports:
      - "7162:7162"
    # 启动环境参数配置
    environment:
      - SERVER_PORT=7162
      - APPLICATION_NAME=tsai-monitor
